name: Requirements Workflow test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.15
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Format
      run: |
        meke format
    - name: Test
      run: |
        make test
